import Foundation
import Testing
@testable import BeadsStatusBar

struct DoltHealthReportTests {
    private func input(
        name: String,
        path: String,
        port: Int?,
        database: String,
        dataDir: [String],
        loadSucceeded: Bool = true
    ) -> DoltHealthEngine.Input {
        DoltHealthEngine.Input(
            projectID: UUID(),
            projectName: name,
            projectPath: path,
            metadata: DoltMetadata(host: "127.0.0.1", port: port, databaseName: database, mode: "server"),
            dataDirDatabases: dataDir,
            loadSucceeded: loadSucceeded
        )
    }

    private let fixedDate = Date(timeIntervalSince1970: 1_800_000_000)

    @Test func reportIncludesProjectHeaderPortAndStorage() {
        let health = DoltHealthEngine.assess([
            input(name: "vocal", path: "/Users/x/vocal", port: 3312, database: "vocal", dataDir: ["vocal"]),
        ])
        let report = DoltHealthEngine.reportText(for: health, generatedAt: fixedDate)

        #expect(report.contains("== vocal (/Users/x/vocal) =="))
        #expect(report.contains("port 3312 (pinned)"))
        #expect(report.contains("database: vocal"))
        #expect(report.contains("in data dir: vocal"))
        #expect(report.contains("No findings."))
    }

    @Test func foreignDatabaseReportNamesOwnerAndMoveCommand() {
        let health = DoltHealthEngine.assess([
            input(name: "host", path: "/Users/x/host", port: 3310, database: "host", dataDir: ["host", "guest"]),
            input(name: "guest", path: "/Users/x/guest", port: 3311, database: "guest", dataDir: ["guest"]),
        ])
        let report = DoltHealthEngine.reportText(for: health, generatedAt: fixedDate)

        #expect(report.contains("Database \"guest\" belongs to guest (/Users/x/guest)."))
        #expect(report.contains("mv -f /Users/x/host/.beads/dolt/guest /Users/x/guest/.beads/dolt/guest"))
        #expect(report.contains("cp -R /Users/x/host/.beads/dolt/guest"))
    }

    @Test func unclaimedForeignDatabaseIsArchivedNotMoved() {
        let health = DoltHealthEngine.assess([
            input(name: "host", path: "/Users/x/host", port: 3310, database: "host", dataDir: ["host", "orphan"]),
        ])
        let report = DoltHealthEngine.reportText(for: health, generatedAt: fixedDate)

        #expect(report.contains("No configured project claims database \"orphan\""))
        #expect(report.contains(".beads/backup/orphan-"))
        #expect(!report.contains("mv -f /Users/x/host/.beads/dolt/orphan /Users/x"))
    }

    @Test func servedElsewhereReportPointsAtHostingRepository() {
        let health = DoltHealthEngine.assess([
            input(name: "wf", path: "/Users/x/wf", port: 3307, database: "wf", dataDir: ["other"]),
            input(name: "vocal", path: "/Users/x/vocal", port: 3312, database: "vocal", dataDir: ["vocal", "wf"]),
        ])
        let report = DoltHealthEngine.reportText(for: health, generatedAt: fixedDate)

        #expect(report.contains("Database \"wf\" currently lives inside vocal (/Users/x/vocal)."))
        #expect(report.contains("mv -f /Users/x/vocal/.beads/dolt/wf /Users/x/wf/.beads/dolt/wf"))
    }

    @Test func portFixCommandsAvoidTakenPorts() {
        let health = DoltHealthEngine.assess([
            input(name: "alpha", path: "/Users/x/alpha", port: nil, database: "alpha", dataDir: ["alpha"]),
            input(name: "beta", path: "/Users/x/beta", port: 3310, database: "beta", dataDir: ["beta"]),
        ])
        // Pretend 3311 is busy so the suggestion must skip to 3312.
        let report = DoltHealthEngine.reportText(
            for: health,
            generatedAt: fixedDate,
            isPortFree: { $0 != 3311 }
        )

        #expect(report.contains("bd dolt set port 3312"))
        #expect(!report.contains("bd dolt set port 3310"))
        #expect(!report.contains("bd dolt set port 3311"))
        #expect(report.contains("cd /Users/x/alpha"))
    }

    @Test func reportCarriesTimestampAndAgentFooter() {
        let health = DoltHealthEngine.assess([
            input(name: "vocal", path: "/Users/x/vocal", port: 3312, database: "vocal", dataDir: ["vocal"]),
        ])
        let report = DoltHealthEngine.reportText(for: health, generatedAt: fixedDate)

        #expect(report.hasPrefix("Beadle Dolt Health Report"))
        #expect(report.contains("Projects assessed: 1."))
        #expect(report.contains("Generated by Beadle's Dolt Health view."))
    }
}
